import { PrismaClient } from '@prisma/client'
import crypto from 'crypto'

const prisma = new PrismaClient()

function hashPassword(password: string): string {
    const salt = crypto.randomBytes(16).toString('hex')
    const hash = crypto.pbkdf2Sync(password, salt, 1000, 64, 'sha512').toString('hex')
    return `${salt}:${hash}`
}

function generateSlug(name: string): string {
    return name.toLowerCase()
        .replace(/'/g, '')
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-|-$/g, '')
}

const products = [
  // ===== SKINCARE =====
  {
    name: "Suma Grand Cleanser",
    slug: "suma-grand-cleanser",
    category: "Skincare",
    description: "Gentle facial cleanser suitable for all skin types. Formulated with advanced anti-aging ingredients to nourish, firm and moisturize skin.",
    price: 3450,
    stock: 100,
    images: JSON.stringify(["https://images.unsplash.com/photo-1556228578-0c98aaae08e1?auto=format&fit=crop&q=80&w=800"]),
    featured: false,
    ingredients: "Niacinamide, lactobacillus/soymilk ferment filtrate, carnosine, tripeptide-1, pentapeptide-3, ascorbic acid, astaxanthin",
    benefits: "Nourishes, firms and moisturizes skin. Suitable for all skin types.",
    usage: "Apply to face morning and evening after cleansing",
    stockUnit: "Tube",
    inStock: true,
  },
  {
    name: "Suma Grand Face Mask",
    slug: "suma-grand-face-mask",
    category: "Skincare",
    description: "Youth Essence Facial Mask for deep nourishment and anti-aging treatment.",
    price: 2800,
    stock: 100,
    images: JSON.stringify(["https://images.unsplash.com/photo-1596755389378-c31d21df4aae?auto=format&fit=crop&q=80&w=800"]),
    featured: false,
    ingredients: "Niacinamide, lactobacillus/soymilk ferment filtrate, ascorbic acid, astaxanthin",
    benefits: "Nourishes and firms skin. Anti-aging. Suitable for all skin types.",
    usage: "Apply to clean face. Leave 15-20 minutes then remove.",
    stockUnit: "Pack",
    inStock: true,
  },
  {
    name: "Suma Grand Toner",
    slug: "suma-grand-toner",
    category: "Skincare",
    description: "Refreshing toner that balances skin and prepares it for further skincare steps.",
    price: 3885,
    stock: 100,
    images: JSON.stringify(["https://images.unsplash.com/photo-1629198688000-ef743fdab0c8?auto=format&fit=crop&q=80&w=800"]),
    featured: false,
    ingredients: "Niacinamide, ascorbic acid, astaxanthin",
    benefits: "Balances skin tone. Suitable for all skin types.",
    usage: "Apply to face after cleansing using cotton pad or hands.",
    stockUnit: "Bottle",
    inStock: true,
  },
  {
    name: "Suma Grand Lotion",
    slug: "suma-grand-lotion",
    category: "Skincare",
    description: "Lightweight moisturizing lotion for daily skin hydration and firmness.",
    price: 4250,
    stock: 100,
    images: JSON.stringify(["https://images.unsplash.com/photo-1556228578-0c98aaae08e1?auto=format&fit=crop&q=80&w=800"]),
    featured: false,
    ingredients: "Niacinamide, peptides, ascorbic acid",
    benefits: "Hydrates and firms skin. Suitable for all skin types.",
    usage: "Apply to face and neck morning and evening.",
    stockUnit: "Bottle",
    inStock: true,
  },
  {
    name: "Suma Grand Cream",
    slug: "suma-grand-cream",
    category: "Skincare",
    description: "Rich anti-aging cream that deeply nourishes and restores skin firmness.",
    price: 5300,
    stock: 100,
    images: JSON.stringify(["https://images.unsplash.com/photo-1556228578-0c98aaae08e1?auto=format&fit=crop&q=80&w=800"]),
    featured: true,
    ingredients: "Niacinamide, peptides, astaxanthin, ascorbic acid",
    benefits: "Restores firmness. Anti-aging. Suitable for all skin types.",
    usage: "Apply to face and neck morning and evening.",
    stockUnit: "Jar",
    inStock: true,
  },
  // ===== NMN COLLECTION =====
  {
    name: "NMN Sharp Mind Capsules",
    slug: "nmn-sharp-mind-capsules",
    category: "NMN Collection",
    description: "Premium brain health formula combining NMN + Resveratrol + Ginkgo Biloba. Uses 14mm tri-particle absorption technology. 60 capsules.",
    price: 24830,
    stock: 50,
    images: JSON.stringify(["https://images.unsplash.com/photo-1550572018-73b3e3a4f4b?auto=format&fit=crop&q=80&w=800"]),
    featured: true,
    ingredients: "NMN, Resveratrol, Ginkgo Biloba Extract, Microcrystalline Cellulose",
    benefits: "Genetic repair as you age. Supports brain health. Not for pregnant women.",
    usage: "2 capsules per day",
    stockUnit: "Bottle of 60 capsules",
    inStock: true,
  },
  {
    name: "NMN Duo Release CR Tablets",
    slug: "nmn-duo-release-cr-tablets",
    category: "NMN Collection",
    description: "Advanced NMN with controlled release technology for 24-hour DNA repair. 30 tablets.",
    price: 17280,
    stock: 50,
    images: JSON.stringify(["https://images.unsplash.com/photo-1550572018-73b3e3a4f4b?auto=format&fit=crop&q=80&w=800"]),
    featured: false,
    ingredients: "Hydroxypropyl Methylcellulose, NMN, Microcrystalline Cellulose, Magnesium Stearate",
    benefits: "Genetic repair. Energy boost. 24hr DNA repair. Not for pregnant women.",
    usage: "1 tablet per day in the morning",
    stockUnit: "Bottle of 30 tablets",
    inStock: true,
  },
  {
    name: "NMN 4500 Capsules",
    slug: "nmn-4500-capsules",
    category: "NMN Collection",
    description: "Premium NMN 4500 for anti-aging DNA repair and energy metabolism. Sirtuin activator for brain and heart health. 30 capsules.",
    price: 22450,
    stock: 50,
    images: JSON.stringify(["https://images.unsplash.com/photo-1550572018-73b3e3a4f4b?auto=format&fit=crop&q=80&w=800"]),
    featured: true,
    ingredients: "NMN, Silicon Dioxide, Stearate",
    benefits: "Anti-aging and gene repair. Boosts energy. Brain and heart health. Not for children and pregnant women.",
    usage: "2 capsules per day",
    stockUnit: "Bottle of 30 capsules",
    inStock: true,
  },
  {
    name: "NMN Coffee",
    slug: "nmn-coffee",
    category: "NMN Collection",
    description: "Premium no-sugar-added coffee latte infused with NMN for longevity and energy. Supports metabolic optimization.",
    price: 3880,
    stock: 100,
    images: JSON.stringify(["https://images.unsplash.com/photo-1495474472287-4d71bc323340?auto=format&fit=crop&q=80&w=800"]),
    featured: false,
    ingredients: "NMN, Instant Coffee Powder, Non-dairy Creamer",
    benefits: "Supports longevity. Promotes energy and endurance. Metabolic optimization. Not for children and pregnant women.",
    usage: "Dissolve 1 sachet in 140ml hot water. 1 sachet 2 times per day. Brew at 80-90°C.",
    stockUnit: "Box of sachets",
    inStock: true,
  },
  {
    name: "YouthEver Sachets",
    slug: "youthever-sachets",
    category: "NMN Collection",
    description: "Powerful antioxidant formula combining Resveratrol and NMN for cellular-level protection. 30 sachets.",
    price: 4650,
    stock: 100,
    images: JSON.stringify(["https://images.unsplash.com/photo-1550572018-73b3e3a4f4b?auto=format&fit=crop&q=80&w=800"]),
    featured: false,
    ingredients: "Resveratrol, NMN, anthocyanins, procyanidins",
    benefits: "Weak immunity. Skin condition. Anti-aging. Applies to all ages.",
    usage: "1 pouch per day",
    stockUnit: "Box of 30 sachets",
    inStock: true,
  },
  // ===== IMMUNE SUPPORT =====
  {
    name: "Refined Yunzhi Essence Capsules",
    slug: "refined-yunzhi-essence-capsules",
    category: "Immune Support",
    description: "Premium Yunzhi extract capsules with 300mg PSP per capsule. Sourced from pure and unpolluted nature. 60 capsules.",
    price: 14500,
    stock: 50,
    images: JSON.stringify(["https://images.unsplash.com/photo-1611241923585-91b4d5fa05b?auto=format&fit=crop&q=80&w=800"]),
    featured: false,
    ingredients: "Refined Yunzhi essence (Polysaccharide-peptide PSP)",
    benefits: "Weak immunity. Post-chemotherapy recovery. Serious immune challenges.",
    usage: "2 capsules twice daily. Consistent use for optimal results.",
    stockUnit: "Box of 60 capsules",
    inStock: true,
  },
  {
    name: "Pure & Broken Ganoderma Spores Capsules",
    slug: "pure-broken-ganoderma-spores-capsules",
    category: "Immune Support",
    description: "Organic Ganoderma spores with 99% extraction technology. Fights disease and reduces risk of illness. 60 capsules.",
    price: 12100,
    stock: 50,
    images: JSON.stringify(["https://images.unsplash.com/photo-1611241923585-91b4d5fa05b?auto=format&fit=crop&q=80&w=800"]),
    featured: false,
    ingredients: "Broken Ganoderma spores",
    benefits: "Weak immunity. Post-operation recovery. Rebuilds immunity. Not for pregnant and lactating women.",
    usage: "2 capsules daily morning or evening.",
    stockUnit: "Box of 60 capsules",
    inStock: true,
  },
  {
    name: "Pure & Broken Ganoderma Spores Oil Deluxe",
    slug: "ganoderma-spores-oil-deluxe",
    category: "Immune Support",
    description: "Premium Ganoderma Spore Oil for overall immunity and wellness. 60 capsules.",
    price: 19865,
    stock: 50,
    images: JSON.stringify(["https://images.unsplash.com/photo-1611241923585-91b4d5fa05b?auto=format&fit=crop&q=80&w=800"]),
    featured: true,
    ingredients: "Ganoderma Spore Oil, Gelatin",
    benefits: "Supports overall immunity. Promotes general wellness.",
    usage: "2 capsules daily morning or evening.",
    stockUnit: "Box of 60 capsules",
    inStock: true,
  },
  {
    name: "Ganoderma Spores Oil Deluxe 3X",
    slug: "ganoderma-spores-oil-deluxe-3x",
    category: "Immune Support",
    description: "3X concentrated Ganoderma Spores Oil. Next level supplement. Comprehensively promotes cardiovascular, metabolic and immune health.",
    price: 19865,
    stock: 50,
    images: JSON.stringify(["https://images.unsplash.com/photo-1611241923585-91b4d5fa05b?auto=format&fit=crop&q=80&w=800"]),
    featured: false,
    ingredients: "Ganoderma Spore Oil (3X concentrated)",
    benefits: "Cardiovascular health. Metabolic function. Immune boost.",
    usage: "As directed",
    stockUnit: "Box of 60 capsules",
    inStock: true,
  },
  // ===== MEN'S HEALTH =====
  {
    name: "Xpower Man Plus Capsules",
    slug: "xpower-man-plus-capsules",
    category: "Men's Health",
    description: "US Patent formula for men's vitality and performance. Five major gold raw materials in scientific ratio. 30 capsules.",
    price: 6530,
    stock: 100,
    images: JSON.stringify(["https://images.unsplash.com/photo-1544005313-94ddf0286cd2?auto=format&fit=crop&q=80&w=800"]),
    featured: false,
    ingredients: "Maca, epimedium, black ginger, L-arginine, taurine",
    benefits: "Improves sex endurance, vitality and sperm motility. For men only.",
    usage: "1-2 capsules daily after meal. Not for women and children.",
    stockUnit: "Bottle of 30 capsules",
    inStock: true,
  },
  {
    name: "Xpower Coffee for Men",
    slug: "xpower-coffee-for-men",
    category: "Men's Health",
    description: "US Patent coffee blend tailor-made for men's vitality and performance. 8 sachets.",
    price: 2350,
    stock: 100,
    images: JSON.stringify(["https://images.unsplash.com/photo-1495474472287-4d71bc323340?auto=format&fit=crop&q=80&w=800"]),
    featured: false,
    ingredients: "Maca extract, tongkat ali extract, epimedium extract, american ginseng extract, coffee latte",
    benefits: "Improves sex endurance, vitality and sperm motility. For men only.",
    usage: "Dissolve 1 sachet in 180ml hot water. 1-2 sachets daily max 5/day.",
    stockUnit: "Box of 8 sachets",
    inStock: true,
  },
  {
    name: "ProstatRelax Capsules",
    slug: "prostatrelax-capsules",
    category: "Men's Health",
    description: "US Patent prostate health capsules. FDA and GMP certified. For men aged 45 and above. 60 capsules.",
    price: 3750,
    stock: 100,
    images: JSON.stringify(["https://images.unsplash.com/photo-1544005313-94ddf0286cd2?auto=format&fit=crop&q=80&w=800"]),
    featured: false,
    ingredients: "Epimedium extract",
    benefits: "Prostate health. Urinary problems. Improves sexual performance. For men 45+.",
    usage: "2 capsules per time three times daily.",
    stockUnit: "Box of 60 capsules",
    inStock: true,
  },
  // ===== WOMEN'S HEALTH =====
  {
    name: "FemiCare Feminine Cleanser",
    slug: "femicare-feminine-cleanser",
    category: "Women's Health",
    description: "Antibacterial feminine cleanser that reinforces vaginal resistance against infection. 180ml.",
    price: 1840,
    stock: 100,
    images: JSON.stringify(["https://images.unsplash.com/photo-1556228578-0c98aaae08e1?auto=format&fit=crop&q=80&w=800"]),
    featured: false,
    ingredients: "Rejuvenating minerals, natural essential oils, multiple vitamins, amino acid, vegetable anti-oxidant",
    benefits: "Reinforces resistance against infection. Eliminates abnormal discharge and odor. For women only.",
    usage: "Wash once a day for 7-10 days as a treatment. External use only.",
    stockUnit: "180ml bottle",
    inStock: true,
  },
  {
    name: "Feminergy Capsules",
    slug: "feminergy-capsules",
    category: "Women's Health",
    description: "Premium grape seed extract from French vineyards. 330mg per capsule. Anti-aging and skin beauty. 60 capsules.",
    price: 6250,
    stock: 100,
    images: JSON.stringify(["https://images.unsplash.com/photo-1556228578-0c98aaae08e1?auto=format&fit=crop&q=80&w=800"]),
    featured: false,
    ingredients: "Grape seed extract 330mg per capsule",
    benefits: "Improves skin tone, elasticity and reduces wrinkles. Treats acne scars. Anti-aging. For women.",
    usage: "1 capsule half an hour after meal twice daily.",
    stockUnit: "Bottle of 60 capsules",
    inStock: true,
  },
  // ===== CHILDREN'S HEALTH =====
  {
    name: "SmartKids Calcium & Vitamin D3 Milk Tablet",
    slug: "smartkids-calcium-vitamin-d3-milk-tablet",
    category: "Children's Health",
    description: "Strawberry flavored calcium tablets for children's bone growth and development. Prevents rickets and osteoporosis. 60 tablets.",
    price: 3150,
    stock: 100,
    images: JSON.stringify(["https://images.unsplash.com/photo-1598300042249-d99aafddd29d?auto=format&fit=crop&q=80&w=800"]),
    featured: false,
    ingredients: "Vitamin D3, Calcium Carbonate, milk and strawberry flavors",
    benefits: "Promotes bone growth. Prevents rickets and osteoporosis. Suitable for children over 3 years.",
    usage: "Children: Chew 1-2 tablets 1-2 times per day. Adults: 1-3 tablets 1-2 times per day.",
    stockUnit: "Bottle of 60 tablets",
    inStock: true,
  },
  {
    name: "SmartKids Sharp Vision Chewable Tablets",
    slug: "smartkids-sharp-vision-chewable-tablets",
    category: "Children's Health",
    description: "Blueberry chewable tablets to support healthy eye growth in children. Protects against myopia and dry eyes.",
    price: 3150,
    stock: 100,
    images: JSON.stringify(["https://images.unsplash.com/photo-1598300042249-d99aafddd29d?auto=format&fit=crop&q=80&w=800"]),
    featured: false,
    ingredients: "Lutein Esters, Blueberry Fruit Powder, Zeaxanthin, Wolfberry Fruit Powder",
    benefits: "Prevents myopia and amblyopia. Relieves dry eyes. Suitable for children over 3 years.",
    usage: "Take 2 tablets daily",
    stockUnit: "Bottle of 90 tablets",
    inStock: true,
  },
  {
    name: "SmartKids Vitamin C 100mg",
    slug: "smartkids-vitamin-c-100mg",
    category: "Children's Health",
    description: "Orange-flavored chewable Vitamin C tablets for children and adults to boost immunity. 120 tablets.",
    price: 2850,
    stock: 100,
    images: JSON.stringify(["https://images.unsplash.com/photo-1598300042249-d99aafddd29d?auto=format&fit=crop&q=80&w=800"]),
    featured: false,
    ingredients: "Vitamin C 100mg",
    benefits: "Vitamin C supplementation. Enhances immune system.",
    usage: "Children 4-13: 1 tablet/day. Adults: 1-5/day.",
    stockUnit: "Bottle of 120 tablets",
    inStock: true,
  },
  // ===== DIGESTIVE HEALTH =====
  {
    name: "ConstiRelax Solution",
    slug: "constirelax-solution",
    category: "Digestive Health",
    description: "Natural constipation relief sachets with Radix Astragali. Promotes regular bowel movement. 30 sachets.",
    price: 3100,
    stock: 100,
    images: JSON.stringify(["https://images.unsplash.com/photo-1550595992-a5eb1de303b2?auto=format&fit=crop&q=80&w=800"]),
    featured: false,
    ingredients: "Radix astragali, FOS (fructooligosaccharide)",
    benefits: "For chronic or acute constipation. Promotes regular bowel movement.",
    usage: "1 sachet before meal twice daily. Half dose for children.",
    stockUnit: "Box of 30 sachets",
    inStock: true,
  },
  {
    name: "Probio3+ Probiotic Sachets",
    slug: "probio3-plus-probiotic-sachets",
    category: "Digestive Health",
    description: "Advanced probiotic formula with 7 live strains and 300 billion live units. Strawberry flavored. 30 sachets.",
    price: 3100,
    stock: 100,
    images: JSON.stringify(["https://images.unsplash.com/photo-1550595992-a5eb1de303b2?auto=format&fit=crop&q=80&w=800"]),
    featured: false,
    ingredients: "Lactobacillus fermentum LF26, Lactobacillus paracasei LPC12, Lactobacillus rhamnosus LRH10, Bifidobacterium longum BL986, Lactobacillus acidophilus LA1063",
    benefits: "Treats constipation or diarrhea. Improves absorption. Boosts weak immune systems. Not for children under 1 year.",
    usage: "Adults: 1-2 sachets/day. Children: 1 sachet/day. Dissolve in water below 45°C.",
    stockUnit: "Box of 30 sachets",
    inStock: true,
  },
  {
    name: "Veggie Veggie Sachets",
    slug: "veggie-veggie-sachets",
    category: "Digestive Health",
    description: "120 fresh vegetable and fruit fermentation essences for digestive health and weight management. 15 sachets.",
    price: 4650,
    stock: 100,
    images: JSON.stringify(["https://images.unsplash.com/photo-1550595992-a5eb1de303b2?auto=format&fit=crop&q=80&w=800"]),
    featured: false,
    ingredients: "Rainbow fruit and vegetable fermentation essence, French Nutriose dietary fiber, six probiotics combination",
    benefits: "Treats constipation and intestinal discomfort. Weight management. Not for children under 1 year.",
    usage: "Brew with 100ml warm or cold water. Adults: 1 sachet/day.",
    stockUnit: "Box of 15 sachets",
    inStock: true,
  },
  // ===== JOINT & BONE HEALTH =====
  {
    name: "ArthroXtra Tablets",
    slug: "arthroxtra-tablets",
    category: "Joint & Bone Health",
    description: "High-concentration glucosamine and chondroitin tablets. 375mg glucosamine + 300mg chondroitin per tablet. 60 tablets.",
    price: 6250,
    stock: 100,
    images: JSON.stringify(["https://images.unsplash.com/photo-1544367567-0f2fcb00935b?auto=format&fit=crop&q=80&w=800"]),
    featured: false,
    ingredients: "Glucosamine hydrochloride, Chondroitin sulfate sodium",
    benefits: "Joint damage recovery. Joint aging concerns. For physically active people.",
    usage: "2 tablets per time twice daily with meals. Take at least 3 weeks for initial effects.",
    stockUnit: "Bottle of 60 tablets",
    inStock: true,
  },
  {
    name: "GluzoJoint Ultra Pro 4in1",
    slug: "gluzojoint-ultra-pro-4in1",
    category: "Joint & Bone Health",
    description: "Advanced 4-in-1 joint and bone formula. Supplements amino sugar, repairs cartilage, prevents osteoporosis.",
    price: 14350,
    stock: 100,
    images: JSON.stringify(["https://images.unsplash.com/photo-1544367567-0f2fcb00935b?auto=format&fit=crop&q=80&w=800"]),
    featured: false,
    ingredients: "Glucosamine hydrochloride, Chondroitin sulfate, Calcium fructose borate, Sodium hyaluronate",
    benefits: "Sedentary lifestyle joint support. Joint deformities. Not for children, teenagers, pregnant and nursing mothers.",
    usage: "2 tablets per day one in morning and night.",
    stockUnit: "Bottle",
    inStock: true,
  },
  {
    name: "ZaminoCal Plus Capsules",
    slug: "zaminocal-plus-capsules",
    category: "Joint & Bone Health",
    description: "Advanced calcium supplement with 95%+ absorption rate. Four elements supplementation. Mild bone activate formula. 60 capsules.",
    price: 6250,
    stock: 100,
    images: JSON.stringify(["https://images.unsplash.com/photo-1544367567-0f2fcb00935b?auto=format&fit=crop&q=80&w=800"]),
    featured: false,
    ingredients: "Calcium amino acid chelate, zinc amino acid chelate, magnesium carbonate, selenium yeast",
    benefits: "Basic care for bones and teeth. For people needing calcium, magnesium, zinc and selenium.",
    usage: "2 capsules per day with meals. Consult physician if pregnant or nursing.",
    stockUnit: "Bottle of 60 capsules",
    inStock: true,
  },
  // ===== BRAIN HEALTH =====
  {
    name: "CereBrain Tablets",
    slug: "cerebrain-tablets",
    category: "Brain Health",
    description: "Ginkgo Biloba extract tablets to improve brain cell metabolism and blood flow. Fights age-related memory loss. 60 tablets.",
    price: 3450,
    stock: 100,
    images: JSON.stringify(["https://images.unsplash.com/photo-1550572018-73b3e3a4f4b?auto=format&fit=crop&q=80&w=800"]),
    featured: false,
    ingredients: "Ginkgo leaves extract",
    benefits: "Mentally demanding lifestyle. Elderly brain health. Prevents headache, memory loss and Alzheimer's. Not for epilepsy patients.",
    usage: "2 tablets per time three times daily",
    stockUnit: "Box of 60 tablets",
    inStock: true,
  },
  // ===== CARDIOVASCULAR HEALTH =====
  {
    name: "Relivin Tea",
    slug: "relivin-tea",
    category: "Cardiovascular Health",
    description: "Premium herbal tea from Luobuma combined with green tea. Supports healthy blood pressure and cholesterol. 20 sachets.",
    price: 2800,
    stock: 100,
    images: JSON.stringify(["https://images.unsplash.com/photo-1560512823-829485b3f84?auto=format&fit=crop&q=80&w=800"]),
    featured: false,
    ingredients: "Folium apocyni veneti and green tea",
    benefits: "Cholesterol and blood pressure management. Anti-aging protection from free radicals.",
    usage: "1 tea bag in boiling water for 10-15 mins. Each bag brews 2-3 times. One bag daily.",
    stockUnit: "Box of 20 sachets",
    inStock: true,
  },
  {
    name: "Micro2 Cycle Tablets",
    slug: "micro2-cycle-tablets",
    category: "Cardiovascular Health",
    description: "Traditional Chinese herb-based cardiovascular health tablets. Supports circulatory system. 100 tablets.",
    price: 3450,
    stock: 100,
    images: JSON.stringify(["https://images.unsplash.com/photo-1560512823-829485b3f84?auto=format&fit=crop&q=80&w=800"]),
    featured: false,
    ingredients: "Radix salvia miltiorrhiza, radix panax notoginseng, borneolum syntheticum",
    benefits: "Cardiovascular health. Prevents thrombosis. Not for pregnant women.",
    usage: "3 tablets per time 3 times daily",
    stockUnit: "Box of 100 tablets",
    inStock: true,
  },
  // ===== BLOOD SUGAR =====
  {
    name: "GymEffect Capsules",
    slug: "gymeffect-capsules",
    category: "Blood Sugar Management",
    description: "Natural blood sugar management capsules with organic chromium and Gymnema Sylvestris. 60 capsules.",
    price: 4350,
    stock: 100,
    images: JSON.stringify(["https://images.unsplash.com/photo-1550595992-a5eb1de303b2?auto=format&fit=crop&q=80&w=800"]),
    featured: false,
    ingredients: "Chromium (Organic from Yeast), Gymnema Sylvestris Extract, Pyrroloquinoline Quinone Disodium Salt",
    benefits: "Blood sugar health. Sugar metabolism. Not for children and pregnant women.",
    usage: "2 capsules daily before meals",
    stockUnit: "Box of 60 capsules",
    inStock: true,
  },
  // ===== WEIGHT MANAGEMENT =====
  {
    name: "Ez-Xlim Tablets",
    slug: "ez-xlim-tablets",
    category: "Weight Management",
    description: "Natural weight management tablets with fat-blocking and starch-blocking formula. US patent technology. 90 tablets.",
    price: 8075,
    stock: 100,
    images: JSON.stringify(["https://images.unsplash.com/photo-1550595992-a5eb1de303b2?auto=format&fit=crop&q=80&w=800"]),
    featured: false,
    ingredients: "Chitosan, white kidney bean, gymnema sylvestre, citrus aurantium",
    benefits: "Weight management. Reduces food cravings. Slim figure. Not for pregnant and lactating women.",
    usage: "3 tablets 15 mins before meal twice daily.",
    stockUnit: "Box of 90 tablets",
    inStock: true,
  },
  // ===== LIVER HEALTH =====
  {
    name: "Detoxilive Soft Gels",
    slug: "detoxilive-soft-gels",
    category: "Liver Health",
    description: "100% natural soy lecithin capsules for liver support and detoxification. 38% Soy PC content. 60 capsules.",
    price: 3200,
    stock: 100,
    images: JSON.stringify(["https://images.unsplash.com/photo-1611241923585-91b4d5fa05b?auto=format&fit=crop&q=80&w=800"]),
    featured: false,
    ingredients: "Soy Lecithin",
    benefits: "Liver health support. For drinkers and sub-health population. Not for pregnant and lactating women.",
    usage: "1 soft gel capsule with meal 3 times daily.",
    stockUnit: "Box of 60 capsules",
    inStock: true,
  },
  // ===== ORAL CARE =====
  {
    name: "Dr.Ts Toothpaste",
    slug: "dr-ts-toothpaste",
    category: "Oral Care",
    description: "Advanced toothpaste with dual active factors - blue cleaning and green herbal factor. 4D Care. 130g.",
    price: 950,
    stock: 100,
    images: JSON.stringify(["https://images.unsplash.com/photo-1556228578-0c98aaae08e1?auto=format&fit=crop&q=80&w=800"]),
    featured: false,
    ingredients: "Blue cleaning factor, green herbal factor, ginseng essence",
    benefits: "Thorough cleaning. Prevents cavities. Nourishes teeth. Freshens breath.",
    usage: "Brush after meals or morning and night for at least 2 mins.",
    stockUnit: "130g tube",
    inStock: true,
  },
  // ===== LIFE ESSENTIALS =====
  {
    name: "CoolRoll Medicated Oil",
    slug: "coolroll-medicated-oil",
    category: "Life Essentials",
    description: "Portable 10ml roller ball medicated oil. Plant-based formula for quick relief from headaches and insect bites.",
    price: 1750,
    stock: 100,
    images: JSON.stringify(["https://images.unsplash.com/photo-1587554371780-5c9e5acdf0?auto=format&fit=crop&q=80&w=800"]),
    featured: false,
    ingredients: "Menthol crystals, menthyl salicylate, camphor, eucalyptus oil, essence oil",
    benefits: "Mosquito bites. Headache, dizziness, fever and carsickness relief. External use only.",
    usage: "Apply roller to area needed. Not for children and pregnant women.",
    stockUnit: "10ml roller",
    inStock: true,
  },
]

async function main() {
  console.log('Seeding database...')

  // Create Admin User
  await prisma.user.upsert({
    where: { email: 'admin@ssm.co.ke' },
    update: {},
    create: {
      email: 'admin@ssm.co.ke',
      name: 'SSM Admin',
      phone: '0796388790',
      password: hashPassword('admin123'),
      role: 'ADMIN',
    }
  })

  // Seed products
  for (const product of products) {
    await prisma.product.upsert({
      where: { slug: product.slug },
      update: product,
      create: product,
    })
  }

  console.log(`✅ Seeded ${products.length} products successfully!`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
